"""Writes the report dataclass created in builder.py
and outputs it as a markdown file for user consumption"""
from __future__ import annotations

from pathlib import Path

from pipesense.reporting.builder import ChannelStats, Report


class ReportWriter:
    """Writes a Report to a Markdown file.

    Usage:
        writer = ReportWriter("reports/summary.md")
        writer.write(report)
    """

    def __init__(self, output_path: Path) -> None:
        self.output_path = Path(output_path)
        self.output_path.parent.mkdir(parents=True, exist_ok=True)

    def write(self, report: Report) -> str:
        """Render the report in the format defined below
        and write it to disk. Returns the rendered string."""

        # [WRITE] Confirm output path before any rendering — wrong path is easier to catch here
        # print(f"[ReportWriter] writing to {self.output_path}")

        md = self.render(report)

        # [WRITE] Character count before the file is created — zero means render produced empty output
        # print(f"[ReportWriter] rendered {len(md)} chars")

        self.output_path.write_text(md, encoding="utf-8")

        # [WRITE] Confirm file landed on disk with final size
        # print(f"[ReportWriter] done  size={self.output_path.stat().st_size} bytes")

        return md

    def render(self, report: Report) -> str:
        def fmt(v: float | None) -> str:
            return f"{v:.3f}" if v is not None else "—"

        lines = [
            "# Pipesense Site Report",
            "",
            f"**Site:** {report.site_id}",
            f"**Run:** {report.run_id}",
            f"**Generated:** {report.generated_at}",
            f"**Total alarms:** {report.total_alarms}",
            "",
            "---",
            "",
            "## Channel Statistics",
            "",
            "| Tag | Samples | Good | Bad | Uncertain | Mean | Std | Min | Max | Alarms |",
            "|-----|---------|------|-----|-----------|------|-----|-----|-----|--------|",
        ]

        for tag_id, cs in sorted(report.channel_stats.items()):
            lines.append(
                f"| {cs.tag_id} | {cs.sample_count} | {cs.good_count} | "
                f"{cs.bad_count} | {cs.uncertain_count} | "
                f"{fmt(cs.mean)} | {fmt(cs.std)} | {fmt(cs.min)} | {fmt(cs.max)} | "
                f"{cs.alarm_count} |"
            )

        lines += ["", "---", "", "## Alarm Summary", ""]

        alarm_rows = [
            (tag_id, sev, count)
            for tag_id, cs in sorted(report.channel_stats.items())
            for sev, count in sorted(cs.alarm_by_severity.items())
        ]

        if alarm_rows:
            lines += [
                "| Tag | Severity | Count |",
                "|-----|----------|-------|",
            ]
            for tag_id, sev, count in alarm_rows:
                lines.append(f"| {tag_id} | {sev} | {count} |")
        else:
            lines.append("No alarms recorded in this run.")

        lines += ["", "---", "_Generated by pipesense_"]
        return "\n".join(lines)